

all: 
	cl /c /EHsc /Fo..\obj\ /I..\include main.cpp 
	cl /c /EHsc /Fo..\obj\ /I..\include lexer.cpp 
	cl /c /EHsc /Fo..\obj\ /I..\include parser.cpp
	cl /c /EHsc /Fo..\obj\ /I..\include parsetree.cpp
	cl /c /EHsc /Fo..\obj\ /I..\include deterministicfa.cpp


